import { HEADERS, VALUE } from './enum.util';

export const READERS_RESPONSE = {
	[HEADERS.CONTENT_TYPE]: VALUE.APPLICATION_JSON,
	[HEADERS.ACCESS_CONTROL_ALLOW_HEADERS]: VALUE.ALLOW,
	[HEADERS.ACCESS_CONTROL_ALLOW_ORIGIN]: VALUE.ALLOW,
	[HEADERS.ACCESS_CONTROL_ALLOW_METHODS]: VALUE.ALLOW,
};
export const nnnn = '';
